<?php
$thegig_slider_sc = thegig_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $thegig_slider_sc ) && strpos( $thegig_slider_sc, '[' ) !== false && strpos( $thegig_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( thegig_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$thegig_anchor_icon = thegig_get_theme_option( 'front_page_title_anchor_icon' );
		$thegig_anchor_text = thegig_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $thegig_anchor_icon ) || ! empty( $thegig_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $thegig_anchor_icon ) ? ' icon="' . esc_attr( $thegig_anchor_icon ) . '"' : '' )
									. ( ! empty( $thegig_anchor_text ) ? ' title="' . esc_attr( $thegig_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $thegig_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$thegig_scheme = thegig_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $thegig_scheme ) && ! thegig_is_inherit( $thegig_scheme ) ) {
			echo ' scheme_' . esc_attr( $thegig_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( thegig_get_theme_option( 'front_page_title_paddings' ) );
		if ( thegig_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$thegig_css      = '';
		$thegig_bg_image = thegig_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $thegig_bg_image ) ) {
			$thegig_css .= 'background-image: url(' . esc_url( thegig_get_attachment_url( $thegig_bg_image ) ) . ');';
		}
		if ( ! empty( $thegig_css ) ) {
			echo ' style="' . esc_attr( $thegig_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$thegig_anchor_icon = thegig_get_theme_option( 'front_page_title_anchor_icon' );
		$thegig_anchor_text = thegig_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $thegig_anchor_icon ) || ! empty( $thegig_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $thegig_anchor_icon ) ? ' icon="' . esc_attr( $thegig_anchor_icon ) . '"' : '' )
									. ( ! empty( $thegig_anchor_text ) ? ' title="' . esc_attr( $thegig_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( thegig_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' thegig-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$thegig_css      = '';
			$thegig_bg_mask  = thegig_get_theme_option( 'front_page_title_bg_mask' );
			$thegig_bg_color_type = thegig_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $thegig_bg_color_type ) {
				$thegig_bg_color = thegig_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $thegig_bg_color_type ) {
				$thegig_bg_color = thegig_get_scheme_color( 'bg_color', $thegig_scheme );
			} else {
				$thegig_bg_color = '';
			}
			if ( ! empty( $thegig_bg_color ) && $thegig_bg_mask > 0 ) {
				$thegig_css .= 'background-color: ' . esc_attr(
					1 == $thegig_bg_mask ? $thegig_bg_color : thegig_hex2rgba( $thegig_bg_color, $thegig_bg_mask )
				) . ';';
			}
			if ( ! empty( $thegig_css ) ) {
				echo ' style="' . esc_attr( $thegig_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$thegig_caption = thegig_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $thegig_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $thegig_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $thegig_caption, 'thegig_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$thegig_description = thegig_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $thegig_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $thegig_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $thegig_description ), 'thegig_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( thegig_get_theme_option( 'front_page_title_button1_link' ) != '' || thegig_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						thegig_show_layout( thegig_customizer_partial_refresh_front_page_title_button1_link() );
						thegig_show_layout( thegig_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
